package Frame;

import Dominio.Jugador;
import callMessage.Mandadero;
import conexionCliente.ClienteSocket;
import enumServicio.EnumServicio;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

public class fmIngresarPartida extends javax.swing.JFrame implements Observer {

    private ClienteSocket cliente;
    private Jugador jugador;
    private int tamTablero;

    public fmIngresarPartida() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Ingresar partida");
        cliente = new ClienteSocket("localhost", 9090);
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent event) {
                fmMenu fmMenu = new fmMenu();
                fmMenu.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIngresarPartida = new javax.swing.JPanel();
        lblIngresarPartida = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        lb_codigo = new javax.swing.JLabel();
        lblNickName = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(558, 275));

        jPanelIngresarPartida.setBackground(new java.awt.Color(105, 2, 5));
        jPanelIngresarPartida.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIngresarPartida.setFont(new java.awt.Font("Herculanum", 0, 20)); // NOI18N
        lblIngresarPartida.setText("Ingresar Partida");
        jPanelIngresarPartida.add(lblIngresarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 58));

        btnIngresar.setBackground(new java.awt.Color(243, 243, 220));
        btnIngresar.setFont(new java.awt.Font("Herculanum", 0, 16)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanelIngresarPartida.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 144, -1));

        btnCancelar.setBackground(new java.awt.Color(243, 243, 220));
        btnCancelar.setFont(new java.awt.Font("Herculanum", 0, 16)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanelIngresarPartida.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 131, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/piramide-maya.png"))); // NOI18N
        jPanelIngresarPartida.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FED148.jpeg"))); // NOI18N
        jPanelIngresarPartida.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 560, 60));

        lb_codigo.setForeground(new java.awt.Color(255, 255, 255));
        jPanelIngresarPartida.add(lb_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 150, 20));

        lblNickName.setFont(new java.awt.Font("PT Sans", 0, 18)); // NOI18N
        lblNickName.setForeground(new java.awt.Color(243, 243, 220));
        lblNickName.setText("Nickname*");
        jPanelIngresarPartida.add(lblNickName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        txtNickname.setBackground(new java.awt.Color(243, 243, 220));
        txtNickname.setFont(new java.awt.Font("PT Sans", 0, 13)); // NOI18N
        txtNickname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNicknameKeyTyped(evt);
            }
        });
        jPanelIngresarPartida.add(txtNickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIngresarPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelIngresarPartida, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        fmMenu frameMenu = new fmMenu();
        frameMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    public boolean validarNickname() {
        return !txtNickname.getText().isEmpty();
    }

    public void iniciarCliente(Jugador jugador) {
        try {

            cliente.iniciar();
            cliente.getBroker().setJugador(jugador);
            cliente.getBroker().addObserver(this);
        } catch (IOException ex) {
            Logger.getLogger(fmCrearPartida.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(fmIngresarPartida.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void abrirSiguientePantalla() {
        fmTablero frameTablero = new fmTablero(tamTablero, jugador, cliente.getBroker());
        frameTablero.setVisible(true);
        this.dispose();

    }

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if (validarNickname()) {
            jugador = new Jugador(txtNickname.getText());
            iniciarCliente(jugador);
            Mandadero mandadero = new Mandadero(EnumServicio.INGRESAR_PARTIDA);
            mandadero.addPeticion("jugador", jugador);
            cliente.getBroker().solicitarPedido(mandadero);
            

        } else {
            lblNickName.setText("*Ingresa tu nickname");
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtNicknameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNicknameKeyTyped
        char a = evt.getKeyChar();
        if ((txtNickname.getText().length() >= 10)) {//que sea menor a 10 letras
            evt.consume();
        }
    }//GEN-LAST:event_txtNicknameKeyTyped

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Images/piramide-maya.png"));

        return retValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelIngresarPartida;
    private javax.swing.JLabel lb_codigo;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIngresarPartida;
    private javax.swing.JLabel lblNickName;
    private javax.swing.JTextField txtNickname;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object o1) {
        Mandadero mandadero = (Mandadero) o1;
        if (mandadero.getRespuesta().containsKey("tamTablero")) {
            this.tamTablero = (int) mandadero.getRespuesta().get("tamTablero");
            abrirSiguientePantalla();
        }
    }
}
