/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Dominio.Jugador;
import Frame.MultiCliente;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.Socket;
import java.net.UnknownHostException;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Diana Jiménez
 */
public class PnlChat extends javax.swing.JPanel {

//    MultiCliente ClientThread;
    private final static String ENTER = "\n";

    /**
     * Creates new form Chat
     * @param jugador
     */
    public PnlChat(Jugador jugador) {
        setLayout(new GroupLayout(this));
//        this.setSize(300, 580);
        initComponents();
        setSize(300, 600);
        this.setLocation(1050, 0);
//        txtMensaje.setEnabled(false);
        txtContenido.setEditable(false);
//        txtMensaje.setEditable(false);
//        try {
//            Socket s = new Socket("localhost", 3333);
//            ClientThread = new MultiCliente(s, this, jugador);
//            ClientThread.start();
//        } catch (UnknownHostException e) {
//            // TODO Auto-generated catch block
//            e.printStackTrace();
//        } catch (IOException e) {
//            // TODO Auto-generated catch block
//            e.printStackTrace();
//        }
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtContenido = new javax.swing.JTextArea();
        txtMensaje = new javax.swing.JTextField();

        setName("ChaTolli"); // NOI18N

        txtContenido.setColumns(20);
        txtContenido.setRows(5);
        jScrollPane1.setViewportView(txtContenido);

        txtMensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMensajeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMensajeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMensajeKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String texto = txtMensaje.getText();
           // texto = String.format("%clientSocket", event.getActionCommand());
//            String text = txtMensaje.getText();
            //ClientThread.ClientOutServerIn(texto);
            txtMensaje.setText("");
        }
    }//GEN-LAST:event_txtMensajeKeyReleased
public void setDisplay(String mensaje) {
        txtContenido.append(mensaje + ENTER);
    }

//if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//            String string= txtNombre.getText();
//            if (string.matches("[0-9]*")) {
//                JOptionPane.showMessageDialog(null, "formato no permitido");
//                txtNombre.setText("");
//            } else {
//                ClientThread.setName(string);
//                ClientThread.SetClient("channel0", string);
//                JOptionPane.showMessageDialog(null, "Nombre de usuario: " + string);
////                    txtNombre.setText("");
//                txtNombre.setEditable(false);
//                txtMensaje.setEnabled(true);
//                txtMensaje.setEditable(true);
//                txtCanal.setEditable(true);
//                ClientThread.ClientOutServerIn("new user");
////                lbNombre.setVisible(false);
//            }
//        }

//    if (evt.getKeyCode () 
//        == KeyEvent.VK_ENTER) {
//            String texto = txtCanal.getText();
////            texto = String.format("%clientSocket", event.getActionCommand());
//        if (texto.matches("[a-z A-Z]")) {
//            JOptionPane.showMessageDialog(null, "formato no permitido");
//            txtCanal.setText("");
//        } else {
//            ClientThread.clientData.SetChannel("Canal" + texto);
//            JOptionPane.showMessageDialog(null, "El canal se ha establecido a: canal" + texto);
//            txtCanal.setText("");
//            ClientThread.ClientOutServerIn("change channel");
//        }

//    public void setUserInChannel(String x) {
//        UserNames.append(x + ENTER);
//    }
//
//    public void ClearDisplay() {
//        UserNames.setText("");
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtContenido;
    private javax.swing.JTextField txtMensaje;
    // End of variables declaration//GEN-END:variables
}
