/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Dominio.Jugador;
import broker.Broker;
import callMessage.Mandadero;
import enumServicio.EnumServicio;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Diana Jiménez
 */
public class PnlChat extends javax.swing.JPanel {
//observer del broker
    private final static String ENTER = "\n";
    Jugador jugador;
    Broker broker;

    /**
     * Creates new form Chat
     *
     * @param jugador
     */
    public PnlChat(Jugador jugador, Broker broker) {
        setLayout(new GroupLayout(this));
        this.setBackground(new Color(105, 2, 5));
        initComponents();
        setSize(300, 600);
        this.setLocation(1050, 0);
        this.jugador=jugador;
        this.broker=broker; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtContenido = new javax.swing.JTextArea();
        txtMensaje = new javax.swing.JTextField();

        setName("ChaTolli"); // NOI18N

        txtContenido.setEditable(false);
        txtContenido.setBackground(new java.awt.Color(235, 222, 206));
        txtContenido.setColumns(20);
        txtContenido.setRows(5);
        txtContenido.setFocusable(false);
        jScrollPane1.setViewportView(txtContenido);

        txtMensaje.setBackground(new java.awt.Color(235, 222, 206));
        txtMensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMensajeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(txtMensaje))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMensajeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMensajeKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String texto = txtMensaje.getText();
            HashMap<String, Object> params= new HashMap<>();
            Mandadero mandadero= new Mandadero(EnumServicio.ENVIAR_MENSAJE);
            mandadero.addPeticion("mensaje", texto);
            mandadero.addPeticion("jugador", jugador);
            this.broker.solicitarPedidoSHEIN(mandadero); //¿dónde? 
//waiteame            //lo quitamos //llega dos veces a nosotros
            txtMensaje.setText("");
            
        }
    }//GEN-LAST:event_txtMensajeKeyReleased
    public void setDisplay(String mensaje) {
        this.txtContenido.append(mensaje+ENTER);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtContenido;
    private javax.swing.JTextField txtMensaje;
    // End of variables declaration//GEN-END:variables
}
